import jsPDF from 'jspdf';
import { GeneratedContent } from './api/contentGenerator';

export const exportContentToPDF = (content: GeneratedContent): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  const addText = (text: string, fontSize: number, isBold = false, color: [number, number, number] = [0, 0, 0]) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    doc.setTextColor(color[0], color[1], color[2]);
    
    const lines = doc.splitTextToSize(text, maxWidth);
    
    lines.forEach((line: string) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, margin, y);
      y += fontSize * 0.5;
    });
    y += 5;
  };

  const addSection = (title: string) => {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }
    y += 5;
    addText(title, 14, true, [79, 70, 229]); // Primary color
    y += 2;
  };

  // Title
  addText(content.topic, 24, true);
  
  // Metadata
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Subject: ${content.subject} | Grade: ${content.grade} | Curriculum: ${content.stream}`, margin, y);
  y += 15;

  // Explanation
  addSection('📚 Topic Explanation');
  addText(content.explanation, 11);
  
  // Key Concepts
  addSection('💡 Key Concepts');
  content.keyConcepts.forEach((concept, i) => {
    addText(`${i + 1}. ${concept.term}`, 12, true);
    addText(concept.definition, 10);
    addText(`Importance: ${concept.importance}`, 10, false, [100, 100, 100]);
    y += 3;
  });

  // Revision Notes
  addSection('📝 Revision Notes');
  content.revisionNotes.forEach((note) => {
    addText(`• ${note}`, 10);
  });

  // Worked Examples
  addSection('📖 Worked Examples');
  content.examples.forEach((example, i) => {
    addText(`Example ${i + 1}:`, 11, true);
    addText(`Problem: ${example.problem}`, 10);
    addText(`Solution: ${example.solution}`, 10, false, [34, 139, 34]);
    y += 5;
  });

  // Practice Questions
  addSection('❓ Practice Questions');
  content.practiceQuestions.forEach((q, i) => {
    addText(`Q${i + 1}: ${q.question}`, 11, true);
    addText(`Answer: ${q.answer}`, 10, false, [34, 139, 34]);
    y += 5;
  });

  // Sources
  if (content.sources.length > 0) {
    addSection('🔗 Sources');
    content.sources.forEach((source) => {
      try {
        const hostname = new URL(source).hostname;
        addText(`• ${hostname}`, 9, false, [100, 100, 100]);
      } catch {
        addText(`• ${source}`, 9, false, [100, 100, 100]);
      }
    });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.text(`Generated by StudyHub AI | Page ${i} of ${pageCount}`, pageWidth / 2, 290, { align: 'center' });
  }

  // Save
  const filename = `${content.topic.replace(/[^a-zA-Z0-9]/g, '_')}_StudyGuide.pdf`;
  doc.save(filename);
};
